spring:
   profiles:
    active: dev
   datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:pandoraAdminApplication;DB_CLOSE_ON_EXIT=FALSE
   jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: h2
        properties:
               hibernate.cache.use_second_level_cache: false
               hibernate.show_sql : true
        hibernate:
          use-new-id-generator-mappings: true

server:
   port: 8080