spring:
    datasource:
        url: jdbc:h2:mem:dynamos
        name:
        username: sa
        password: pass
    h2:
        console:
            enabled: false
    jpa:
        database-platform:  org.hibernate.dialect.H2Dialect
        database: h2
        show_sql: true
        properties:
            hibernate.hbm2ddl.auto : create
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory


server:
    port: 8080
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json